# Generated by Django 4.0.4 on 2022-05-28 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_item', models.CharField(max_length=50)),
                ('name_of_item', models.CharField(max_length=50)),
                ('qty_available', models.IntegerField(default=0)),
                ('last_issued', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('no_of_issued_items', models.IntegerField(default=0)),
                ('unique_code', models.CharField(max_length=10)),
            ],
        ),
    ]
