# Generated by Django 4.0.4 on 2022-05-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnapp', '0003_alter_items_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='unique_code',
            field=models.IntegerField(default=26717507, editable=False),
        ),
    ]
