# Generated by Django 4.0.4 on 2022-05-29 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fnapp', '0004_alter_items_unique_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='issue_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_borrower', models.CharField(max_length=50)),
                ('email_of_borrower', models.EmailField(max_length=254)),
                ('time_of_issue', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='unique_code',
            field=models.IntegerField(default=44161344, editable=False),
        ),
    ]
