# Generated by Django 4.0.4 on 2022-05-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnapp', '0005_issue_items_items_added_on_alter_items_unique_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue_items',
            old_name='name_of_borrower',
            new_name='username_of_borrower',
        ),
        migrations.AddField(
            model_name='issue_items',
            name='borrowed_item_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='unique_code',
            field=models.IntegerField(default=77167307, editable=False),
        ),
    ]
