# Generated by Django 4.0.4 on 2022-05-31 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fnapp', '0006_rename_name_of_borrower_issue_items_username_of_borrower_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_item', models.CharField(max_length=20)),
                ('name_of_item', models.CharField(max_length=20)),
                ('total_qty', models.IntegerField(default=0)),
                ('current_out', models.IntegerField(default=0)),
                ('unique_code', models.IntegerField(default=26509028, editable=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(editable=False, max_length=15)),
                ('last_name', models.CharField(editable=False, max_length=15)),
                ('email_id', models.EmailField(editable=False, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Through',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_issued', models.IntegerField(default=1)),
                ('time_of_issue', models.DateTimeField(auto_now_add=True)),
                ('time_of_return', models.DateTimeField()),
                ('qty_returned', models.IntegerField(default=0)),
                ('is_returned', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fnapp.item')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fnapp.student')),
            ],
        ),
        migrations.DeleteModel(
            name='issue_items',
        ),
        migrations.DeleteModel(
            name='items',
        ),
    ]
