# Generated by Django 4.0.4 on 2022-06-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnapp', '0008_alter_item_unique_code_alter_through_time_of_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unique_code',
            field=models.IntegerField(default=63786115, editable=False),
        ),
    ]
