# Generated by Django 4.0.4 on 2022-06-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnapp', '0009_alter_item_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='through',
            name='time_of_issue_int',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='unique_code',
            field=models.IntegerField(default=72315813, editable=False),
        ),
    ]
