# Generated by Django 4.0.4 on 2022-06-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnapp', '0011_through_current_issued_alter_item_unique_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unique_code',
            field=models.IntegerField(default=24689594, editable=False),
        ),
    ]
