# Generated by Django 4.0.4 on 2022-06-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnapp', '0018_remove_student_user_alter_item_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unique_code',
            field=models.IntegerField(default=17800208, editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=15),
        ),
    ]
